name: Docker Build

on:
  push:
    branches:
      - main

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Build Docker Image
      run: |
        docker build -t my-python-app .

    - name: Run Docker Container
      run: |
        docker run -d -p 8501:8501 --name my-running-app my-python-app

    - name: Wait for Container
      run: |
        sleep 10  # Wait for container to start

    - name: Verify App
      run: |
        curl http://localhost:8000
